export const OCCUPATION_OPTIONS = [
    "Private Service",
    "Business/Entrepreneur",
    "Agriculture/Farming",
    "Doctor",
    "Engineer",
    "Lawyer",
    "Retired",
    "Government Service",
    "Self-Employed",
    "Freelancer",
    "Teacher/Educator",
    "Housewife",
    "Laborer/Skilled Worker",
    "Student",
    "Scientist/Researcher",
    "Artist/Performer",
    "Shopkeeper/Trader",
    "Healthcare Worker (Nurse, Pharmacist, etc.)",
    "Security Services",
    "Driver/Chauffeur",
    "Construction Worker",
    "IT Professional/Software Engineer",
    "Journalist/Media",
    "Banking/Finance",
    "Real Estate",
    "Architect",
    "Fashion Designer",
    "Government Contractor",
    "NGO Worker",
    "Mechanic",
    "Chef/Caterer",
    "Sportsperson",
    "Civil Services (IAS, IPS, etc.)",
    "Clerical/Administrative",
    "Others",
].map(o => ({ value: o, label: o }));
